apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - semaphore
  selector:
    matchLabels:
      app: envoy-gateway
      component: admin
  endpoints:
    - port: envoy-admin
      path: /stats/prometheus
      interval: 30s
      scheme: http
