apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: semaphore-istio-proxy
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - semaphore
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - auth-identity
          - academics
          - attendance
          - beacon
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 30s
