apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - semaphore-servicemonitor.yaml
  - semaphore-envoy-servicemonitor.yaml
  - promtail-config.yaml

configMapGenerator:
  - name: semaphore-grafana-dashboard
    files:
      - dashboards/semaphore-dashboard.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
    app: semaphore
    grafana_folder: semaphore
    release: kube-prometheus-stack
