apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: semaphore

resources:
  - k8s/semaphore-stack.yaml
  - k8s/istio

configMapGenerator:
  - name: envoy-gateway-config
    files:
      - envoy.yaml=docker/envoy/envoy.yaml

generatorOptions:
  disableNameSuffixHash: true