apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: semaphore

resources:
  - k8s/semaphore-stack.yaml

configMapGenerator:
  - name: envoy-config
    files:
      - envoy.yaml=docker/envoy/envoy.yaml
  - name: migrations-auth-identity
    files:
      - migrations/auth_identity
  - name: migrations-academics
    files:
      - migrations/academics
  - name: migrations-attendance
    files:
      - migrations/attendance
  - name: migrations-beacon
    files:
      - migrations/beacon

generatorOptions:
  disableNameSuffixHash: true
