apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: semaphore

resources:
  - k8s/semaphore-stack.yaml

configMapGenerator:
  - name: envoy-config
    files:
      - envoy.yaml=docker/envoy/envoy.yaml

generatorOptions:
  disableNameSuffixHash: true
