apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - semaphore-namespace.yaml
  - semaphore-gateway.yaml
  - semaphore-mtls.yaml
  - semaphore-ingress-auth.yaml
  - semaphore-observability-authz.yaml
