apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: semaphore-ingress-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: "semaphore-auth-identity"
      jwksUri: "http://auth-identity.semaphore.svc.cluster.local:8081/.well-known/jwks.json"
      forwardOriginalToken: true

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: semaphore-ingress-authz
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
    - to:
        - operation:
            paths:
              - /auth*
              - /beacon*
              - /.well-known*
              - /health*
    - from:
        - source:
            requestPrincipals: ["*"]
