apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: semaphore
spec:
  mtls:
    mode: STRICT

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default
  namespace: semaphore
spec:
  host: "*.semaphore.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: semaphore-mtls-egress
  namespace: istio-system
spec:
  host: "*.semaphore.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-semaphore-namespace
  namespace: semaphore
spec:
  action: ALLOW
  rules:
    - {}

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: envoy-gateway-permissive
  namespace: semaphore
spec:
  selector:
    matchLabels:
      app: envoy-gateway
  mtls:
    mode: PERMISSIVE

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: auth-identity-permissive
  namespace: semaphore
spec:
  selector:
    matchLabels:
      app: auth-identity
  mtls:
    mode: PERMISSIVE

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: academics-permissive
  namespace: semaphore
spec:
  selector:
    matchLabels:
      app: academics
  mtls:
    mode: PERMISSIVE

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: attendance-permissive
  namespace: semaphore
spec:
  selector:
    matchLabels:
      app: attendance
  mtls:
    mode: PERMISSIVE

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: beacon-permissive
  namespace: semaphore
spec:
  selector:
    matchLabels:
      app: beacon
  mtls:
    mode: PERMISSIVE

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-envoy-gateway-public
  namespace: semaphore
spec:
  selector:
    matchLabels:
      app: envoy-gateway
  action: ALLOW
  rules:
    - {}
